### ISSUE TITLE
Decode Pipeline Stops/Starts Playback of MP3 Randomly

### ISSUE THREAD

**Issue by ns96** [ns96/cassetteflow#3]
The decode pipeline stops/starts the playback of mp3s randomly. Tested using different mp3 files of various sizes, and on two different boards. This doesn't seem to be caused by bad data read either. 

![decode_bug](https://user-images.githubusercontent.com/835756/145570388-e8e04c02-d25f-4ed4-9397-03ea189117df.png)

**Comment by vovan888** [comment]
@ns96 could you please check if those mp3 files are VBR or CBR?

**Comment by vovan888** [comment]
@ns96 please try the latest update if it fixed the issue

**Comment by ns96** [comment]
I suspect this issue likely due to the tape running "too" fast based on looking at the code and testing with the Java version. The code changes you made will allow me to confirm this and the fix would just be using 5 seconds instead of 2 seconds on line pipeline_decode.c. Will test and let you know
